// megafunction wizard: %LPM_ADD_SUB%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: LPM_ADD_SUB 

// ============================================================
// File Name: conditional_adder.v
// Megafunction Name(s):
// 			LPM_ADD_SUB
//
// Simulation Library Files(s):
// 			lpm
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 24.1std.0 Build 1077 03/04/2025 SC Lite Edition
// ************************************************************


//Copyright (C) 2025  Altera Corporation. All rights reserved.
//Your use of Altera Corporation's design tools, logic functions 
//and other software and tools, and any partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Altera Program License 
//Subscription Agreement, the Altera Quartus Prime License Agreement,
//the Altera IP License Agreement, or other applicable license
//agreement, including, without limitation, that your use is for
//the sole purpose of programming logic devices manufactured by
//Altera and sold by Altera or its authorized distributors.  Please
//refer to the Altera Software License Subscription Agreements 
//on the Quartus Prime software download page.


//lpm_add_sub DEVICE_FAMILY="MAX II" LPM_DIRECTION="SUB" LPM_REPRESENTATION="UNSIGNED" LPM_WIDTH=6 ONE_INPUT_IS_CONSTANT="YES" dataa datab result
//VERSION_BEGIN 24.1 cbx_cycloneii 2025:03:05:20:06:36:SC cbx_lpm_add_sub 2025:03:05:20:06:36:SC cbx_mgl 2025:03:05:20:07:01:SC cbx_nadder 2025:03:05:20:06:36:SC cbx_stratix 2025:03:05:20:06:36:SC cbx_stratixii 2025:03:05:20:06:36:SC  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463


//synthesis_resources = lut 6 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  conditional_adder_add_sub
	( 
	dataa,
	datab,
	result) /* synthesis synthesis_clearbox=1 */;
	input   [5:0]  dataa;
	input   [5:0]  datab;
	output   [5:0]  result;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [5:0]  dataa;
	tri0   [5:0]  datab;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [5:0]   wire_add_sub_cella_combout;
	wire  [0:0]   wire_add_sub_cella_0cout;
	wire  [0:0]   wire_add_sub_cella_1cout;
	wire  [0:0]   wire_add_sub_cella_2cout;
	wire  [0:0]   wire_add_sub_cella_3cout;
	wire  [0:0]   wire_add_sub_cella_4cout;
	wire  [5:0]   wire_add_sub_cella_dataa;
	wire  [5:0]   wire_add_sub_cella_datab;

	maxii_lcell   add_sub_cella_0
	( 
	.cin(1'b1),
	.combout(wire_add_sub_cella_combout[0:0]),
	.cout(wire_add_sub_cella_0cout[0:0]),
	.dataa(wire_add_sub_cella_dataa[0:0]),
	.datab(wire_add_sub_cella_datab[0:0]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_0.cin_used = "true",
		add_sub_cella_0.lut_mask = "69b2",
		add_sub_cella_0.operation_mode = "arithmetic",
		add_sub_cella_0.sum_lutc_input = "cin",
		add_sub_cella_0.lpm_type = "maxii_lcell";
	maxii_lcell   add_sub_cella_1
	( 
	.cin(wire_add_sub_cella_0cout[0:0]),
	.combout(wire_add_sub_cella_combout[1:1]),
	.cout(wire_add_sub_cella_1cout[0:0]),
	.dataa(wire_add_sub_cella_dataa[1:1]),
	.datab(wire_add_sub_cella_datab[1:1]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_1.cin_used = "true",
		add_sub_cella_1.lut_mask = "69b2",
		add_sub_cella_1.operation_mode = "arithmetic",
		add_sub_cella_1.sum_lutc_input = "cin",
		add_sub_cella_1.lpm_type = "maxii_lcell";
	maxii_lcell   add_sub_cella_2
	( 
	.cin(wire_add_sub_cella_1cout[0:0]),
	.combout(wire_add_sub_cella_combout[2:2]),
	.cout(wire_add_sub_cella_2cout[0:0]),
	.dataa(wire_add_sub_cella_dataa[2:2]),
	.datab(wire_add_sub_cella_datab[2:2]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_2.cin_used = "true",
		add_sub_cella_2.lut_mask = "69b2",
		add_sub_cella_2.operation_mode = "arithmetic",
		add_sub_cella_2.sum_lutc_input = "cin",
		add_sub_cella_2.lpm_type = "maxii_lcell";
	maxii_lcell   add_sub_cella_3
	( 
	.cin(wire_add_sub_cella_2cout[0:0]),
	.combout(wire_add_sub_cella_combout[3:3]),
	.cout(wire_add_sub_cella_3cout[0:0]),
	.dataa(wire_add_sub_cella_dataa[3:3]),
	.datab(wire_add_sub_cella_datab[3:3]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_3.cin_used = "true",
		add_sub_cella_3.lut_mask = "69b2",
		add_sub_cella_3.operation_mode = "arithmetic",
		add_sub_cella_3.sum_lutc_input = "cin",
		add_sub_cella_3.lpm_type = "maxii_lcell";
	maxii_lcell   add_sub_cella_4
	( 
	.cin(wire_add_sub_cella_3cout[0:0]),
	.combout(wire_add_sub_cella_combout[4:4]),
	.cout(wire_add_sub_cella_4cout[0:0]),
	.dataa(wire_add_sub_cella_dataa[4:4]),
	.datab(wire_add_sub_cella_datab[4:4]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_4.cin_used = "true",
		add_sub_cella_4.lut_mask = "69b2",
		add_sub_cella_4.operation_mode = "arithmetic",
		add_sub_cella_4.sum_lutc_input = "cin",
		add_sub_cella_4.lpm_type = "maxii_lcell";
	maxii_lcell   add_sub_cella_5
	( 
	.cin(wire_add_sub_cella_4cout[0:0]),
	.combout(wire_add_sub_cella_combout[5:5]),
	.cout(),
	.dataa(wire_add_sub_cella_dataa[5:5]),
	.datab(wire_add_sub_cella_datab[5:5]),
	.regout(),
	.aclr(1'b0),
	.aload(1'b0),
	.clk(1'b0),
	.datac(1'b1),
	.datad(1'b1),
	.ena(1'b1),
	.inverta(1'b0),
	.regcascin(1'b0),
	.sclr(1'b0),
	.sload(1'b0)
	// synopsys translate_off
	,
	.cin0(1'b0),
	.cin1(1'b1),
	.cout0(),
	.cout1(),
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		add_sub_cella_5.cin_used = "true",
		add_sub_cella_5.lut_mask = "6969",
		add_sub_cella_5.operation_mode = "normal",
		add_sub_cella_5.sum_lutc_input = "cin",
		add_sub_cella_5.lpm_type = "maxii_lcell";
	assign
		wire_add_sub_cella_dataa = dataa,
		wire_add_sub_cella_datab = datab;
	assign
		result = wire_add_sub_cella_combout;
endmodule //conditional_adder_add_sub
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module conditional_adder (
	dataa,
	result)/* synthesis synthesis_clearbox = 1 */;

	input	[5:0]  dataa;
	output	[5:0]  result;

	wire [5:0] sub_wire0 = 6'h24;
	wire [5:0] sub_wire1;
	wire [5:0] result = sub_wire1[5:0];

	conditional_adder_add_sub	conditional_adder_add_sub_component (
				.dataa (dataa),
				.datab (sub_wire0),
				.result (sub_wire1));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: CarryIn NUMERIC "0"
// Retrieval info: PRIVATE: CarryOut NUMERIC "0"
// Retrieval info: PRIVATE: ConstantA NUMERIC "0"
// Retrieval info: PRIVATE: ConstantB NUMERIC "36"
// Retrieval info: PRIVATE: Function NUMERIC "1"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "MAX II"
// Retrieval info: PRIVATE: LPM_PIPELINE NUMERIC "1"
// Retrieval info: PRIVATE: Latency NUMERIC "0"
// Retrieval info: PRIVATE: Overflow NUMERIC "0"
// Retrieval info: PRIVATE: RadixA NUMERIC "10"
// Retrieval info: PRIVATE: RadixB NUMERIC "10"
// Retrieval info: PRIVATE: Representation NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: ValidCtA NUMERIC "0"
// Retrieval info: PRIVATE: ValidCtB NUMERIC "1"
// Retrieval info: PRIVATE: WhichConstant NUMERIC "2"
// Retrieval info: PRIVATE: aclr NUMERIC "0"
// Retrieval info: PRIVATE: clken NUMERIC "1"
// Retrieval info: PRIVATE: nBit NUMERIC "6"
// Retrieval info: PRIVATE: new_diagram STRING "1"
// Retrieval info: LIBRARY: lpm lpm.lpm_components.all
// Retrieval info: CONSTANT: LPM_DIRECTION STRING "SUB"
// Retrieval info: CONSTANT: LPM_HINT STRING "ONE_INPUT_IS_CONSTANT=YES,CIN_USED=NO"
// Retrieval info: CONSTANT: LPM_REPRESENTATION STRING "UNSIGNED"
// Retrieval info: CONSTANT: LPM_TYPE STRING "LPM_ADD_SUB"
// Retrieval info: CONSTANT: LPM_WIDTH NUMERIC "6"
// Retrieval info: USED_PORT: dataa 0 0 6 0 INPUT NODEFVAL "dataa[5..0]"
// Retrieval info: USED_PORT: result 0 0 6 0 OUTPUT NODEFVAL "result[5..0]"
// Retrieval info: CONNECT: @dataa 0 0 6 0 dataa 0 0 6 0
// Retrieval info: CONNECT: @datab 0 0 6 0 36 0 0 6 0
// Retrieval info: CONNECT: result 0 0 6 0 @result 0 0 6 0
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder.inc TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder.cmp TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder_inst.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL conditional_adder_syn.v TRUE
// Retrieval info: LIB_FILE: lpm
