// clk_src.v

// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module clk_src (
		output wire  clk  // clk.clk
	);

	altera_avalon_clock_source #(
		.CLOCK_RATE (50),
		.CLOCK_UNIT (1000000)
	) clock_source_0 (
		.clk (clk)  // clk.clk
	);

endmodule
